import { StyleSheet, Dimensions, Platform } from "react-native";

const { width: SCREEN_WIDTH } = Dimensions.get("window");
export { SCREEN_WIDTH };

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0f172a",
  },
  loadingText: {
    color: "#f1f5f9",
    fontSize: 16,
    textAlign: "center",
  },
  content: {
    flex: 1,
    padding: 24,
    paddingBottom: 24,
  },
  btn: {
    borderRadius: 11,
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
  },
  btnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 14,
  },
  btnPrimary: { backgroundColor: "#6366f1" },
  btnWorker: { backgroundColor: "#f59e0b" },
  btnSupplier: { backgroundColor: "#8b5cf6" },
  btnGeneral: { backgroundColor: "#f43f5e" },
  btnIncome: { backgroundColor: "#6366f1" },
  btnExpense: { backgroundColor: "#f43f5e" },
  dashboard: { gap: 20 },
  statsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 14 },
  statCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderRadius: 16,
    padding: 20,
    minWidth: 150,
    flex: 1,
  },
  statIcon: { fontSize: 26 },
  statLabel: { color: "#94a3b8", fontSize: 12, marginTop: 6 },
  statValue: { fontSize: 22, fontWeight: "800", marginTop: 4 },
  card: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.09)",
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
  },
  cardTitle: {
    color: "#c4b5fd",
    fontSize: 15,
    marginBottom: 16,
    fontWeight: "700",
  },
  chart: { marginVertical: 8, borderRadius: 16 },
  clientSummaryItem: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.07)",
  },
  clientSummaryInfo: { flex: 1 },
  clientSummaryName: { fontWeight: "700", fontSize: 15, color: "#f1f5f9" },
  clientSummaryProject: { color: "#64748b", fontSize: 12 },
  statusBadge: { borderRadius: 20, paddingVertical: 2, paddingHorizontal: 10 },
  statusText: { fontSize: 11, fontWeight: "700" },
  clientSummaryProfit: { alignItems: "flex-end", minWidth: 110 },
  clientSummaryProfitText: { fontWeight: "800", fontSize: 15 },
  clientSummaryProfitLabel: { color: "#64748b", fontSize: 11 },
  emptyState: { alignItems: "center", paddingVertical: 60 },
  emptyIcon: { fontSize: 52 },
  emptyText: { color: "#475569", marginTop: 10 },
  clientsView: { gap: 16 },
  sectionSubtitle: { color: "#64748b", fontSize: 13, marginBottom: 16 },
  clientsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  clientCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.09)",
    borderRadius: 16,
    padding: 14,
    minWidth: 280,
    flex: 1,
  },
  clientCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  clientCardName: { fontWeight: "800", fontSize: 16, color: "#f1f5f9" },
  clientCardMeta: { color: "#64748b", fontSize: 13, marginTop: 2 },
  clientCardStats: { flexDirection: "row", gap: 6 },
  clientCardStat: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.05)",
    borderRadius: 8,
    padding: 6,
    alignItems: "center",
  },
  clientCardStatLabel: { color: "#64748b", fontSize: 11 },
  clientCardStatValue: { fontWeight: "700", fontSize: 13, marginTop: 4 },
  clientDetail: { gap: 20 },
  clientDetailHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
    marginBottom: 20,
  },
  clientDetailHeaderStack: {
    flexDirection: "column",
    alignItems: "stretch",
    gap: 14,
    marginBottom: 20,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.08)",
    borderRadius: 16,
    padding: 16,
  },
  clientDetailBackRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  clientDetailHeaderBtnRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 4,
  },
  clientDetailHeaderBtn: {
    flex: 1,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  clientDetailHeaderTop: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 8,
  },
  clientDetailHeaderActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  backBtn: {
    backgroundColor: "rgba(255,255,255,0.07)",
    borderRadius: 11,
    paddingVertical: 8,
    paddingHorizontal: 14,
  },
  backBtnText: { color: "#94a3b8", fontSize: 14 },
  clientDetailInfo: { flex: 1 },
  clientDetailName: { fontSize: 20, fontWeight: "800", color: "#f1f5f9" },
  clientDetailMeta: { color: "#64748b", fontSize: 13 },
  statusBtn: {
    borderRadius: 11,
    paddingVertical: 7,
    paddingHorizontal: 14,
    borderWidth: 1,
  },
  statusBtnText: { fontSize: 14, fontWeight: "700" },
  deleteBtn: {
    backgroundColor: "rgba(244,63,94,0.12)",
    borderWidth: 1,
    borderColor: "rgba(244,63,94,0.3)",
    borderRadius: 11,
    paddingVertical: 7,
    paddingHorizontal: 14,
  },
  deleteBtnText: { color: "#f43f5e", fontSize: 14 },
  clientDetailStats: { flexDirection: "row", gap: 12, marginBottom: 20 },
  clientDetailStatCard: {
    flex: 1,
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderRadius: 16,
    padding: 20,
    alignItems: "center",
  },
  clientDetailStatLabel: { color: "#94a3b8", fontSize: 12 },
  clientDetailStatValue: { fontSize: 20, fontWeight: "800", marginTop: 6 },
  clientDetailActions: { flexDirection: "row", gap: 10, marginBottom: 20 },
  txList: { gap: 10 },
  txItem: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderRadius: 13,
    padding: 13,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  txItemStack: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderRadius: 13,
    padding: 14,
    flexDirection: "column",
    alignItems: "stretch",
    gap: 10,
  },
  txItemRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 8,
  },
  txItemActionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 4,
  },
  txItemButtons: { flexDirection: "row", gap: 8 },
  txIcon: { fontSize: 22 },
  txContent: { flex: 1 },
  txTags: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    flexWrap: "wrap",
  },
  tag: { borderRadius: 20, paddingVertical: 2, paddingHorizontal: 10 },
  tagText: { fontSize: 12, fontWeight: "600" },
  txNote: { color: "#94a3b8", fontSize: 13 },
  txDate: { color: "#475569", fontSize: 12, marginTop: 4 },
  txAmount: {
    fontWeight: "800",
    fontSize: 16,
    minWidth: 100,
    textAlign: "left",
  },
  txEditBtn: {
    backgroundColor: "rgba(129,140,248,0.15)",
    borderWidth: 1,
    borderColor: "rgba(129,140,248,0.3)",
    borderRadius: 11,
    paddingVertical: 5,
    paddingHorizontal: 11,
  },
  txEditBtnText: { color: "#818cf8", fontSize: 12 },
  txDeleteBtn: {
    backgroundColor: "rgba(244,63,94,0.12)",
    borderWidth: 1,
    borderColor: "rgba(244,63,94,0.25)",
    borderRadius: 11,
    paddingVertical: 5,
    paddingHorizontal: 11,
  },
  txDeleteBtnText: { color: "#f43f5e", fontSize: 12 },
  workersView: { gap: 16 },
  workersGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  workerCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.09)",
    borderRadius: 16,
    padding: 14,
    minWidth: 280,
    flex: 1,
  },
  workerCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  workerCardName: { fontWeight: "800", fontSize: 16, color: "#f1f5f9" },
  workerCardPhone: { color: "#64748b", fontSize: 13, marginTop: 2 },
  workerCardActions: { flexDirection: "row", gap: 6 },
  iconBtn: {
    backgroundColor: "rgba(129,140,248,0.15)",
    borderWidth: 1,
    borderColor: "rgba(129,140,248,0.3)",
    borderRadius: 11,
    paddingVertical: 5,
    paddingHorizontal: 10,
  },
  iconBtnDanger: {
    backgroundColor: "rgba(244,63,94,0.12)",
    borderColor: "rgba(244,63,94,0.25)",
  },
  iconBtnText: { fontSize: 12 },
  workerCardStats: {
    backgroundColor: "rgba(245,158,11,0.1)",
    borderRadius: 10,
    padding: 10,
    alignItems: "center",
  },
  workerCardStatsLabel: { color: "#94a3b8", fontSize: 11 },
  workerCardStatsValue: { color: "#f59e0b", fontSize: 18, fontWeight: "800", marginTop: 3 },
  workerCardStatsCount: { color: "#64748b", fontSize: 10, marginTop: 3 },
  workerDetail: { gap: 20 },
  workerDetailHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
    marginBottom: 20,
  },
  workerDetailInfo: { flex: 1 },
  workerDetailName: { fontSize: 20, fontWeight: "800", color: "#f1f5f9" },
  workerDetailMeta: { color: "#64748b", fontSize: 13, marginRight: 12 },
  editBtn: {
    backgroundColor: "rgba(129,140,248,0.15)",
    borderWidth: 1,
    borderColor: "rgba(129,140,248,0.3)",
    borderRadius: 11,
    paddingVertical: 7,
    paddingHorizontal: 14,
  },
  editBtnText: { color: "#818cf8", fontSize: 14 },
  workerDetailStatsLabel: { color: "#94a3b8", fontSize: 13 },
  workerDetailStatsValue: { color: "#f59e0b", fontSize: 28, fontWeight: "900", marginTop: 6 },
  workerDetailStatsCount: { color: "#64748b", fontSize: 12, marginTop: 4 },
  suppliersView: { gap: 16 },
  suppliersGrid: { flexDirection: "row", flexWrap: "wrap", gap: 12 },
  supplierCard: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.09)",
    borderRadius: 16,
    padding: 14,
    minWidth: 280,
    flex: 1,
  },
  supplierCardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 10,
  },
  supplierCardName: { fontWeight: "800", fontSize: 16, color: "#f1f5f9" },
  supplierCardCategory: { color: "#a78bfa", fontSize: 12, marginTop: 2 },
  supplierCardPhone: { color: "#64748b", fontSize: 13, marginTop: 2 },
  supplierCardActions: { flexDirection: "row", gap: 6 },
  supplierCardStats: {
    backgroundColor: "rgba(139,92,246,0.1)",
    borderRadius: 10,
    padding: 10,
    alignItems: "center",
  },
  supplierCardStatsLabel: { color: "#94a3b8", fontSize: 11 },
  supplierCardStatsValue: { color: "#a78bfa", fontSize: 18, fontWeight: "800", marginTop: 3 },
  supplierCardStatsCount: { color: "#64748b", fontSize: 10, marginTop: 3 },
  supplierDetail: { gap: 20 },
  supplierDetailHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flexWrap: "wrap",
    marginBottom: 20,
  },
  supplierDetailInfo: { flex: 1 },
  supplierDetailName: { fontSize: 20, fontWeight: "800", color: "#f1f5f9" },
  supplierDetailMeta: { color: "#64748b", fontSize: 13, marginRight: 12 },
  supplierDetailStatsLabel: { color: "#94a3b8", fontSize: 13 },
  supplierDetailStatsValue: { color: "#a78bfa", fontSize: 28, fontWeight: "900", marginTop: 6 },
  supplierDetailStatsCount: { color: "#64748b", fontSize: 12, marginTop: 4 },
  generalView: { gap: 20 },
  generalStatsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 20,
  },
  generalStatLabel: { color: "#94a3b8", fontSize: 12 },
  generalStatValue: { color: "#f43f5e", fontWeight: "800", fontSize: 18, marginTop: 6 },
  generalStatCurrency: { color: "#64748b", fontSize: 11 },
  zakatView: {
    gap: 20,
    maxWidth: 560,
    alignSelf: "center",
    width: "100%",
  },
  zakatHeader: { alignItems: "center", marginBottom: 28 },
  zakatIcon: { fontSize: 52 },
  zakatTitle: {
    marginTop: 10,
    marginBottom: 4,
    fontSize: 22,
    fontWeight: "800",
    color: "#c4b5fd",
  },
  zakatSubtitle: { color: "#64748b", fontSize: 13 },
  zakatNissabRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    flexWrap: "wrap",
  },
  zakatNissabLabel: { fontWeight: "700", fontSize: 14, color: "#c4b5fd" },
  zakatNissabSubtext: { color: "#64748b", fontSize: 12, marginTop: 3 },
  zakatNissabInput: { flexDirection: "row", alignItems: "center", gap: 8 },
  zakatNissabCurrency: { color: "#94a3b8", fontSize: 13 },
  zakatDetails: { gap: 10 },
  zakatDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: "rgba(255,255,255,0.03)",
    borderRadius: 10,
  },
  zakatDetailRowTotal: {
    borderTopWidth: 1,
    borderTopColor: "rgba(255,255,255,0.1)",
    paddingTop: 10,
    backgroundColor: "rgba(255,255,255,0.05)",
  },
  zakatDetailLabel: { color: "#94a3b8", fontSize: 14 },
  zakatDetailLabelTotal: { color: "#f1f5f9", fontWeight: "700", fontSize: 14 },
  zakatDetailValue: { fontWeight: "700", fontSize: 14 },
  zakatDetailValueTotal: { fontWeight: "800", fontSize: 15 },
  zakatResultIcon: { fontSize: 40, marginBottom: 10 },
  zakatResultText: { color: "#94a3b8", fontSize: 14, marginBottom: 8 },
  zakatResultAmount: { color: "#10b981", fontSize: 36, fontWeight: "900" },
  zakatResultCurrency: { color: "#10b981", fontSize: 16, marginTop: 4 },
  zakatResultFormula: { color: "#64748b", fontSize: 12, marginTop: 12 },
  zakatResultMessage: {
    marginTop: 16,
    backgroundColor: "rgba(16,185,129,0.1)",
    borderWidth: 1,
    borderColor: "rgba(16,185,129,0.2)",
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  zakatResultMessageText: { color: "#10b981", fontSize: 13, fontWeight: "700" },
  zakatResultSubtext: { color: "#64748b", fontSize: 13, marginTop: 8 },
  zakatResultSubtextHighlight: { color: "#818cf8", fontWeight: "700" },
  zakatWarningTitle: { color: "#f59e0b", fontSize: 12, fontWeight: "700", marginBottom: 4 },
  zakatWarningText: { color: "#94a3b8", fontSize: 12, lineHeight: 20 },
  modalTitle: {
    color: "#c4b5fd",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 20,
  },
  inputGroup: { marginBottom: 14 },
  inputLabel: { color: "#94a3b8", fontSize: 13, marginBottom: 6 },
  input: {
    width: "100%",
    backgroundColor: "rgba(255,255,255,0.07)",
    borderWidth: 2,
    borderColor: "rgba(255,255,255,0.12)",
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 14,
    color: "#f1f5f9",
    fontSize: 15,
    ...(Platform.OS === "android"
      ? {
          includeFontPadding: false,
          textAlignVertical: "center",
        }
      : {}),
  },
  inputFocused: {
    borderColor: "#818cf8",
    backgroundColor: "rgba(129,140,248,0.08)",
  },
  optionsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  optionBtn: {
    backgroundColor: "rgba(255,255,255,0.07)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.13)",
    borderRadius: 11,
    paddingVertical: 6,
    paddingHorizontal: 14,
  },
  optionBtnActive: {
    backgroundColor: "#6366f1",
    borderColor: "#6366f1",
  },
  optionBtnText: { color: "#fff", fontSize: 14, fontWeight: "400" },
  optionBtnTextActive: { fontWeight: "700" },
  modalSaveBtn: { width: "100%", paddingVertical: 12, marginBottom: 8 },
  modalSubtitle: { color: "#64748b", fontSize: 13, marginBottom: 18 },
  pickerContainer: { position: "relative" },
  pickerBtn: {
    backgroundColor: "rgba(129,140,248,0.15)",
    borderWidth: 1,
    borderColor: "rgba(129,140,248,0.35)",
    borderRadius: 11,
    paddingVertical: 10,
    paddingHorizontal: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
  },
  pickerBtnText: { color: "#94a3b8", fontSize: 14 },
  pickerBtnArrow: { color: "#818cf8" },
  pickerDropdown: {
    position: "absolute",
    top: "110%",
    right: 0,
    left: 0,
    backgroundColor: "#1e1b4b",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    borderRadius: 12,
    padding: 8,
    zIndex: 100,
    maxHeight: 200,
  },
  pickerList: { maxHeight: 180 },
  pickerItem: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 8,
    marginBottom: 2,
  },
  pickerItemActive: { backgroundColor: "rgba(129,140,248,0.2)" },
  pickerItemText: { color: "#94a3b8", fontSize: 13 },
  pickerItemTextActive: { color: "#818cf8" },
  fiscalYearView: { gap: 16 },
  fiscalYearTitle: { fontSize: 22, fontWeight: "800", color: "#f1f5f9" },
  fiscalYearList: { gap: 10 },
  fiscalYearItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.09)",
    borderRadius: 16,
    padding: 14,
  },
  fiscalYearItemActive: {
    borderColor: "rgba(99,102,241,0.5)",
    backgroundColor: "rgba(99,102,241,0.08)",
  },
  fiscalYearItemTouch: { flex: 1, flexDirection: "row", alignItems: "center" },
  fiscalYearRadioWrap: {
    justifyContent: "center",
    alignItems: "center",
    marginEnd: 12,
  },
  fiscalYearRadioOuter: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: "rgba(148,163,184,0.4)",
    alignItems: "center",
    justifyContent: "center",
  },
  fiscalYearRadioOuterActive: {
    borderColor: "#818cf8",
  },
  fiscalYearRadioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: "#818cf8",
  },
  fiscalYearItemContent: { flex: 1, gap: 4 },
  fiscalYearItemLabel: { fontSize: 16, fontWeight: "700", color: "#f1f5f9" },
  fiscalYearItemLabelActive: { color: "#a5b4fc" },
  fiscalYearItemMeta: { color: "#64748b", fontSize: 13 },
  fiscalYearBadge: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(16,185,129,0.2)",
    borderRadius: 8,
    paddingVertical: 4,
    paddingHorizontal: 10,
    marginTop: 6,
  },
  fiscalYearBadgeText: { color: "#10b981", fontSize: 12, fontWeight: "700" },
  fiscalYearDeleteBtn: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginRight: 8,
  },
  fiscalYearAddBtn: { width: "100%", paddingVertical: 14 },
  backupView: { gap: 16 },
  backupTitle: { fontSize: 22, fontWeight: "800", color: "#f1f5f9" },
  backupHint: { color: "#64748b", fontSize: 13, lineHeight: 20 },
  backupActionsRow: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
  backupBtnSecondary: { backgroundColor: "rgba(148,163,184,0.25)" },
  backupList: { gap: 10 },
  backupItem: {
    backgroundColor: "rgba(255,255,255,0.04)",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.09)",
    borderRadius: 16,
    padding: 14,
  },
  backupItemName: { fontSize: 15, fontWeight: "700", color: "#f1f5f9" },
  backupItemMeta: { color: "#64748b", fontSize: 12, marginTop: 6 },
  backupOpenLink: { marginTop: 10, alignSelf: "flex-start" },
  backupOpenLinkText: { color: "#818cf8", fontSize: 13, fontWeight: "600" },
  backupErrorText: { color: "#f87171", fontSize: 13, marginTop: 8 },
  backupPrivacyBox: {
    backgroundColor: "rgba(99,102,241,0.08)",
    borderWidth: 1,
    borderColor: "rgba(129,140,248,0.35)",
    borderRadius: 14,
    padding: 14,
    gap: 8,
  },
  backupPrivacyTitle: { color: "#c4b5fd", fontSize: 14, fontWeight: "800" },
  backupPrivacyLine: { color: "#94a3b8", fontSize: 13, lineHeight: 21 },
  drawerContent: {
    position: "absolute",
    top: 0,
    right: 0,
    width: SCREEN_WIDTH * 0.75,
    maxWidth: 320,
    height: "100%",
    backgroundColor: "#1e1b4b",
    borderLeftWidth: 1,
    borderLeftColor: "rgba(255,255,255,0.1)",
    shadowColor: "#000",
    shadowOffset: { width: -2, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    zIndex: 10000,
    elevation: 10000,
  },
});
